version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: docker build -t corecrypto-dependencies:latest . -f docker/go-dependencies.Dockerfile --build-arg="CMAKE_BUILD_TYPE=DEBUG"
     - run: docker build -t corecrypto-java:latest . -f docker/java.Dockerfile --build-arg="BUILD_TYPE=debug"
     # - run: docker build -t corecrypto-wasm:latest . -f docker/wasm.Dockerfile
     - run: docker build -t corecrypto:latest . -f docker/go.Dockerfile
     - run: |
         if [ "${CIRCLE_BRANCH}" = "master" ]; then
             docker build -t corecrypto-dependencies:latest . -f docker/go-dependencies.Dockerfile --build-arg="CMAKE_BUILD_TYPE=RELEASE"
             docker build -t corecrypto:latest . -f docker/go.Dockerfile
             $(aws ecr get-login --no-include-email --region us-east-2)
             if [ ! -z "${CIRCLE_TAG}" ]; then
               docker tag corecrypto-dependencies:latest 716293438869.dkr.ecr.us-east-2.amazonaws.com/corecrypto-dependencies:${CIRCLE_TAG}
               docker push 716293438869.dkr.ecr.us-east-2.amazonaws.com/corecrypto-dependencies:${CIRCLE_TAG}
               docker tag corecrypto:latest 716293438869.dkr.ecr.us-east-2.amazonaws.com/corecrypto:${CIRCLE_TAG}
               docker push 716293438869.dkr.ecr.us-east-2.amazonaws.com/corecrypto:${CIRCLE_TAG}
             else
               docker tag corecrypto-dependencies:latest 716293438869.dkr.ecr.us-east-2.amazonaws.com/corecrypto-dependencies:latest
               docker push 716293438869.dkr.ecr.us-east-2.amazonaws.com/corecrypto-dependencies:latest
               docker tag corecrypto:latest 716293438869.dkr.ecr.us-east-2.amazonaws.com/corecrypto:latest
               docker push 716293438869.dkr.ecr.us-east-2.amazonaws.com/corecrypto:latest
             fi
         fi
