version: 2
jobs:

  build-c:
    machine: true
    steps:
      - checkout
      - run: docker build . -f docker/test.Dockerfile --build-arg="CMAKE_BUILD_TYPE=DEBUG"

  build-golang:
    machine: true
    steps:
      - checkout
      - run: docker build -t corecrypto-dependencies:latest . -f docker/go-dependencies.Dockerfile --build-arg="CMAKE_BUILD_TYPE=DEBUG"
      - run: docker build -t corecrypto:latest . -f docker/go.Dockerfile
      - run: |
          if [ "${CIRCLE_BRANCH}" = "master" ]; then
            docker build -t corecrypto-dependencies:latest . -f docker/go-dependencies.Dockerfile --build-arg="CMAKE_BUILD_TYPE=RELEASE"
            docker build -t corecrypto:latest . -f docker/go.Dockerfile
            $(aws ecr get-login --no-include-email --region us-east-2)
            docker tag corecrypto-dependencies:latest 716293438869.dkr.ecr.us-east-2.amazonaws.com/corecrypto-dependencies:latest
            docker push 716293438869.dkr.ecr.us-east-2.amazonaws.com/corecrypto-dependencies:latest
            docker tag corecrypto:latest 716293438869.dkr.ecr.us-east-2.amazonaws.com/corecrypto:latest
            docker push 716293438869.dkr.ecr.us-east-2.amazonaws.com/corecrypto:latest
          fi

  build-ios:
    machine: true
    macos:
      xcode: "10.2.0"
    steps:
      - checkout
      - run: cd bin && ./release-ios.sh .. first

workflows:
  build:
    jobs:
      - build-c
      - build-golang
      - build-ios
